version: "3.8"

services:
  backend:
    container_name: refinitivApp
    build: .
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - redis
    restart: on-failure
    command: python manage.py runserver 0.0.0.0:8000

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    restart: always
    volumes:
      - redisdata:/data

  celery:
    build: .
    command: celery -A refinitivApp worker --loglevel=info
    depends_on:
      - redis
    volumes:
      - .:/app

  flower:
    build: .
    command: celery -A refinitivApp flower
    depends_on:
      - backend
      - redis
      - celery
    environment:
      - DEBUG=1
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    ports:
      - 5555:5555

volumes:
  redisdata: