version: "3.8"

services:
  backend:
    container_name: refinitive_app
    build: .
    ports:
      - 8000:8000
    volumes:
      - .:/app
    restart: on-failure
    command: python manage.py runserver 0.0.0.0:8000
