insert into esg_api_corp (id, title, ticker, industry_type) values (1, 'Biostar Pharmaceuticals, Inc.', 'jbanbridge0', 'Major Pharmaceuticals');
insert into esg_api_corp (id, title, ticker, industry_type) values (2, 'Pioneer Natural Resources Company', 'fbalstone1', 'Oil & Gas Production');
insert into esg_api_corp (id, title, ticker, industry_type) values (3, 'First Trust TCW Opportunistic Fixed Income ETF', 'dfranckton2', 'n/a');
insert into esg_api_corp (id, title, ticker, industry_type) values (4, 'WashingtonFirst Bankshares Inc', 'cbrotherwood3', 'Major Banks');
insert into esg_api_corp (id, title, ticker, industry_type) values (5, 'China Recycling Energy Corporation', 'ncrowche4', 'Business Services');
insert into esg_api_corp (id, title, ticker, industry_type) values (6, 'Nuveen Floating Rate Income Fund', 'tpariso5', 'n/a');
insert into esg_api_corp (id, title, ticker, industry_type) values (7, 'First Trust Hong Kong AlphaDEX Fund', 'smalcolmson6', 'n/a');
insert into esg_api_corp (id, title, ticker, industry_type) values (8, 'Marriott International', 'csibbson7', 'Hotels/Resorts');
insert into esg_api_corp (id, title, ticker, industry_type) values (9, 'Buckeye Partners L.P.', 'bvockins8', 'Natural Gas Distribution');
insert into esg_api_corp (id, title, ticker, industry_type) values (10, 'The Hain Celestial Group, Inc.', 'kketchen9', 'Packaged Foods');
insert into esg_api_corp (id, title, ticker, industry_type) values (11, 'Payment Data Systems, Inc.', 'rgazeya', 'Investment Bankers/Brokers/Service');
insert into esg_api_corp (id, title, ticker, industry_type) values (12, 'Ritter Pharmaceuticals, Inc.', 'ghaskettb', 'Major Pharmaceuticals');
insert into esg_api_corp (id, title, ticker, industry_type) values (13, 'Empire State Realty Trust, Inc.', 'wmanterfieldc', 'Real Estate Investment Trusts');
insert into esg_api_corp (id, title, ticker, industry_type) values (14, 'New York & Company, Inc.', 'rdundond', 'Clothing/Shoe/Accessory Stores');
insert into esg_api_corp (id, title, ticker, industry_type) values (15, 'T. Rowe Price Group, Inc.', 'adailye', 'Investment Bankers/Brokers/Service');
insert into esg_api_corp (id, title, ticker, industry_type) values (16, 'Public Service Enterprise Group Incorporated', 'mkeyzmanf', 'Power Generation');
insert into esg_api_corp (id, title, ticker, industry_type) values (17, 'Tenet Healthcare Corporation', 'tshadfourthg', 'Hospital/Nursing Management');
insert into esg_api_corp (id, title, ticker, industry_type) values (18, 'Select Medical Holdings Corporation', 'sscawtonh', 'Hospital/Nursing Management');
insert into esg_api_corp (id, title, ticker, industry_type) values (19, 'Public Service Enterprise Group Incorporated', 'kblacksteri', 'Power Generation');
insert into esg_api_corp (id, title, ticker, industry_type) values (20, 'Global Partner Acquisition Corp.', 'cbrettlej', 'Hospital/Nursing Management');
insert into esg_api_corp (id, title, ticker, industry_type) values (21, 'Investment Technology Group, Inc.', 'wginnerk', 'Investment Bankers/Brokers/Service');
insert into esg_api_corp (id, title, ticker, industry_type) values (22, 'Gazit-Globe Ltd.', 'dhuguenetl', 'Real Estate');
insert into esg_api_corp (id, title, ticker, industry_type) values (23, 'First Trust Small Cap Growth AlphaDEX Fund', 'ncarvilm', 'n/a');
insert into esg_api_corp (id, title, ticker, industry_type) values (24, 'TPG Pace Energy Holdings Corp.', 'bdowelln', 'n/a');
insert into esg_api_corp (id, title, ticker, industry_type) values (25, 'Newmont Mining Corporation', 'athornbarrowo', 'Precious Metals');
insert into esg_api_corp (id, title, ticker, industry_type) values (26, 'Oxford Immunotec Global PLC', 'aburnerp', 'Biotechnology: In Vitro & In Vivo Diagnostic Substances');
insert into esg_api_corp (id, title, ticker, industry_type) values (27, 'Madison Strategic Sector Premium Fund', 'ajaquemarq', 'n/a');
insert into esg_api_corp (id, title, ticker, industry_type) values (28, 'Teekay Offshore Partners L.P.', 'fstaffr', 'Marine Transportation');
insert into esg_api_corp (id, title, ticker, industry_type) values (29, 'PPL Corporation', 'jharrows', 'Electric Utilities: Central');
insert into esg_api_corp (id, title, ticker, industry_type) values (30, 'MGP Ingredients, Inc.', 'nscrannyt', 'Beverages (Production/Distribution)');
insert into esg_api_corp (id, title, ticker, industry_type) values (31, 'Goldman Sachs MLP Income Opportunities Fund', 'kthomkinsu', 'n/a');
insert into esg_api_corp (id, title, ticker, industry_type) values (32, 'LINE Corporation', 'ahastonv', 'Computer Software: Programming, Data Processing');
insert into esg_api_corp (id, title, ticker, industry_type) values (33, 'Sealed Air Corporation', 'sbresnerw', 'Major Chemicals');
insert into esg_api_corp (id, title, ticker, industry_type) values (34, 'The GDL Fund', 'aadrainx', 'n/a');
insert into esg_api_corp (id, title, ticker, industry_type) values (35, 'Andina Acquisition Corp. II', 'deisoldy', 'Business Services');
insert into esg_api_corp (id, title, ticker, industry_type) values (36, 'National Research Corporation', 'griseamz', 'Biotechnology: Commercial Physical & Biological Resarch');
insert into esg_api_corp (id, title, ticker, industry_type) values (37, 'MarineMax, Inc.', 'vornells10', 'Other Specialty Stores');
insert into esg_api_corp (id, title, ticker, industry_type) values (38, 'Sundance Energy Australia Limited', 'gcowoppe11', 'Oil & Gas Production');
insert into esg_api_corp (id, title, ticker, industry_type) values (39, 'Public Storage', 'ekropp12', 'Real Estate Investment Trusts');
insert into esg_api_corp (id, title, ticker, industry_type) values (40, 'Gamco Investors, Inc.', 'ploos13', 'Investment Bankers/Brokers/Service');
insert into esg_api_corp (id, title, ticker, industry_type) values (41, 'BioShares Biotechnology Products Fund', 'amontez14', 'n/a');
insert into esg_api_corp (id, title, ticker, industry_type) values (42, 'Donnelley Financial Solutions, Inc.', 'tscurrer15', 'Other Consumer Services');
insert into esg_api_corp (id, title, ticker, industry_type) values (43, 'Guggenheim Credit Allocation Fund', 'vcowland16', 'n/a');
insert into esg_api_corp (id, title, ticker, industry_type) values (44, 'Yield10 Bioscience, Inc.', 'ethurley17', 'Containers/Packaging');
insert into esg_api_corp (id, title, ticker, industry_type) values (45, 'Array BioPharma Inc.', 'tharriagn18', 'Major Pharmaceuticals');
insert into esg_api_corp (id, title, ticker, industry_type) values (46, 'Gabelli Global Small and Mid Cap Value Trust (The)', 'tabriani19', 'n/a');
insert into esg_api_corp (id, title, ticker, industry_type) values (47, 'Invesco Mortgage Capital Inc.', 'gschutter1a', 'n/a');
insert into esg_api_corp (id, title, ticker, industry_type) values (48, 'The Providence Service Corporation', 'bdarnborough1b', 'Transportation Services');
insert into esg_api_corp (id, title, ticker, industry_type) values (49, 'Helmerich & Payne, Inc.', 'fbyrom1c', 'Oil & Gas Production');
insert into esg_api_corp (id, title, ticker, industry_type) values (50, 'Cable One, Inc.', 'eoshea1d', 'Television Services');
insert into esg_api_corp (id, title, ticker, industry_type) values (51, 'Catalyst Pharmaceuticals, Inc.', 'nparkeson1e', 'Major Pharmaceuticals');
insert into esg_api_corp (id, title, ticker, industry_type) values (52, 'ACI Worldwide, Inc.', 'dwingeatt1f', 'Computer Software: Prepackaged Software');
insert into esg_api_corp (id, title, ticker, industry_type) values (53, 'Oncobiologics, Inc.', 'cswannick1g', 'Biotechnology: Biological Products (No Diagnostic Substances)');
insert into esg_api_corp (id, title, ticker, industry_type) values (54, 'National Storage Affiliates Trust', 'gjudkin1h', 'Real Estate Investment Trusts');
insert into esg_api_corp (id, title, ticker, industry_type) values (55, 'Cerecor Inc.', 'lcureton1i', 'Major Pharmaceuticals');
insert into esg_api_corp (id, title, ticker, industry_type) values (56, 'Dominion Energy, Inc.', 'abeurich1j', 'Electric Utilities: Central');
insert into esg_api_corp (id, title, ticker, industry_type) values (57, 'MB Financial Inc.', 'smckissack1k', 'Major Banks');
insert into esg_api_corp (id, title, ticker, industry_type) values (58, 'LTC Properties, Inc.', 'ssuthren1l', 'Real Estate Investment Trusts');
insert into esg_api_corp (id, title, ticker, industry_type) values (59, 'Norbord Inc.', 'tferrettini1m', 'Forest Products');
insert into esg_api_corp (id, title, ticker, industry_type) values (60, 'U.S. Bancorp', 'edevil1n', 'n/a');
insert into esg_api_corp (id, title, ticker, industry_type) values (61, 'Sierra Wireless, Inc.', 'gmckeran1o', 'Radio And Television Broadcasting And Communications Equipment');
insert into esg_api_corp (id, title, ticker, industry_type) values (62, 'Sportsman''s Warehouse Holdings, Inc.', 'ogilberthorpe1p', 'Other Specialty Stores');
insert into esg_api_corp (id, title, ticker, industry_type) values (63, 'CSP Inc.', 'abarhems1q', 'EDP Services');
insert into esg_api_corp (id, title, ticker, industry_type) values (64, 'E.I. du Pont de Nemours and Company', 'rfardy1r', 'Major Chemicals');
insert into esg_api_corp (id, title, ticker, industry_type) values (65, 'Maxim Integrated Products, Inc.', 'easpell1s', 'Semiconductors');
insert into esg_api_corp (id, title, ticker, industry_type) values (66, 'Fifth Street Finance Corp.', 'dhirsthouse1t', 'n/a');
insert into esg_api_corp (id, title, ticker, industry_type) values (67, 'Soligenix, Inc.', 'awilfinger1u', 'Major Pharmaceuticals');
insert into esg_api_corp (id, title, ticker, industry_type) values (68, 'LaSalle Hotel Properties', 'bborland1v', 'n/a');
insert into esg_api_corp (id, title, ticker, industry_type) values (69, 'Royal Bank Scotland plc (The)', 'epinel1w', 'n/a');
insert into esg_api_corp (id, title, ticker, industry_type) values (70, 'Gevo, Inc.', 'chawkswood1x', 'Major Chemicals');
insert into esg_api_corp (id, title, ticker, industry_type) values (71, 'iRobot Corporation', 'jcunnane1y', 'Consumer Electronics/Appliances');
insert into esg_api_corp (id, title, ticker, industry_type) values (72, 'First Trust Eurozone AlphaDEX ETF', 'rdigginson1z', 'n/a');
insert into esg_api_corp (id, title, ticker, industry_type) values (73, 'Prudential Financial, Inc.', 'ealdins20', 'Life Insurance');
insert into esg_api_corp (id, title, ticker, industry_type) values (74, 'Kellogg Company', 'aluddy21', 'Packaged Foods');
insert into esg_api_corp (id, title, ticker, industry_type) values (75, 'Pointer Telocation Ltd.', 'relsmere22', 'Radio And Television Broadcasting And Communications Equipment');
insert into esg_api_corp (id, title, ticker, industry_type) values (76, 'PennTex Midstream Partners, LP', 'jmcelhinney23', 'Natural Gas Distribution');
insert into esg_api_corp (id, title, ticker, industry_type) values (77, 'Banco De Chile', 'bpuncher24', 'Commercial Banks');
insert into esg_api_corp (id, title, ticker, industry_type) values (78, '180 Degree Capital Corp.', 'dshenfish25', 'Finance/Investors Services');
insert into esg_api_corp (id, title, ticker, industry_type) values (79, 'Bank of America Corporation', 'cpack26', 'n/a');
insert into esg_api_corp (id, title, ticker, industry_type) values (80, 'Sears Canada Inc. ', 'nlewknor27', 'Department/Specialty Retail Stores');
insert into esg_api_corp (id, title, ticker, industry_type) values (81, 'Atlassian Corporation Plc', 'dbertolin28', 'Computer Software: Prepackaged Software');
insert into esg_api_corp (id, title, ticker, industry_type) values (82, 'Sears Holdings Corporation', 'grouchy29', 'Department/Specialty Retail Stores');
insert into esg_api_corp (id, title, ticker, industry_type) values (83, 'ENI S.p.A.', 'mdehmel2a', 'Oil & Gas Production');
insert into esg_api_corp (id, title, ticker, industry_type) values (84, 'Seaspan Corporation', 'sscandrett2b', 'Marine Transportation');
insert into esg_api_corp (id, title, ticker, industry_type) values (85, 'Bankwell Financial Group, Inc.', 'srowlin2c', 'Major Banks');
insert into esg_api_corp (id, title, ticker, industry_type) values (86, 'Home BancShares, Inc.', 'abernardot2d', 'Major Banks');
insert into esg_api_corp (id, title, ticker, industry_type) values (87, 'OneBeacon Insurance Group, Ltd.', 'elinthead2e', 'Property-Casualty Insurers');
insert into esg_api_corp (id, title, ticker, industry_type) values (88, 'Computer Programs and Systems, Inc.', 'aruncieman2f', 'EDP Services');
insert into esg_api_corp (id, title, ticker, industry_type) values (89, 'CVB Financial Corporation', 'smishow2g', 'Major Banks');
insert into esg_api_corp (id, title, ticker, industry_type) values (90, 'Newtek Business Services Corp.', 'sblitzer2h', 'n/a');
insert into esg_api_corp (id, title, ticker, industry_type) values (91, 'Virtus Global Dividend & Income Fund Inc.', 'mtavner2i', 'n/a');
insert into esg_api_corp (id, title, ticker, industry_type) values (92, 'Titan International, Inc.', 'cfrugier2j', 'Steel/Iron Ore');
insert into esg_api_corp (id, title, ticker, industry_type) values (93, 'Sun Communities, Inc.', 'sdumbleton2k', 'Real Estate Investment Trusts');
insert into esg_api_corp (id, title, ticker, industry_type) values (94, 'CoreCivic, Inc.', 'kreddle2l', 'Real Estate Investment Trusts');
insert into esg_api_corp (id, title, ticker, industry_type) values (95, 'Nuveenn Intermediate Duration Quality Municipal Term Fund', 'aolennane2m', 'n/a');
insert into esg_api_corp (id, title, ticker, industry_type) values (96, 'Endo International plc', 'ndhooge2n', 'Major Pharmaceuticals');
insert into esg_api_corp (id, title, ticker, industry_type) values (97, 'Celsius Holdings, Inc.', 'gexcell2o', 'Beverages (Production/Distribution)');
insert into esg_api_corp (id, title, ticker, industry_type) values (98, 'TriCo Bancshares', 'gcristou2p', 'Major Banks');
insert into esg_api_corp (id, title, ticker, industry_type) values (99, 'Fortress Transportation and Infrastructure Investors LLC', 'gbattisson2q', 'n/a');
insert into esg_api_corp (id, title, ticker, industry_type) values (100, 'Randgold Resources Limited', 'ntarbet2r', 'Precious Metals');

insert into esg_api_esgscore (rank, total_industries, esg_score, environment_pillar, governance_pillar, social_pillar, corp_id) values (39, 483, 99, 96, 10, 69, 1);
insert into esg_api_esgscore (rank, total_industries, esg_score, environment_pillar, governance_pillar, social_pillar, corp_id) values (165, 352, 56, 80, 19, 10, 2);
insert into esg_api_esgscore (rank, total_industries, esg_score, environment_pillar, governance_pillar, social_pillar, corp_id) values (162, 166, 81, 55, 57, 20, 3);
insert into esg_api_esgscore (rank, total_industries, esg_score, environment_pillar, governance_pillar, social_pillar, corp_id) values (132, 112, 59, 22, 95, 59, 4);
insert into esg_api_esgscore (rank, total_industries, esg_score, environment_pillar, governance_pillar, social_pillar, corp_id) values (182, 491, 44, 44, 68, 1, 5);
insert into esg_api_esgscore (rank, total_industries, esg_score, environment_pillar, governance_pillar, social_pillar, corp_id) values (92, 500, 12, 63, 32, 90, 6);
insert into esg_api_esgscore (rank, total_industries, esg_score, environment_pillar, governance_pillar, social_pillar, corp_id) values (182, 360, 3, 85, 46, 93, 7);
insert into esg_api_esgscore (rank, total_industries, esg_score, environment_pillar, governance_pillar, social_pillar, corp_id) values (19, 492, 45, 81, 0, 1, 8);
insert into esg_api_esgscore (rank, total_industries, esg_score, environment_pillar, governance_pillar, social_pillar, corp_id) values (44, 194, 84, 17, 19, 33, 9);
insert into esg_api_esgscore (rank, total_industries, esg_score, environment_pillar, governance_pillar, social_pillar, corp_id) values (74, 133, 30, 53, 57, 35, 10);
insert into esg_api_esgscore (rank, total_industries, esg_score, environment_pillar, governance_pillar, social_pillar, corp_id) values (54, 307, 95, 75, 99, 22, 11);
insert into esg_api_esgscore (rank, total_industries, esg_score, environment_pillar, governance_pillar, social_pillar, corp_id) values (40, 266, 77, 96, 31, 80, 12);
insert into esg_api_esgscore (rank, total_industries, esg_score, environment_pillar, governance_pillar, social_pillar, corp_id) values (107, 401, 92, 29, 40, 41, 13);
insert into esg_api_esgscore (rank, total_industries, esg_score, environment_pillar, governance_pillar, social_pillar, corp_id) values (50, 264, 16, 84, 97, 16, 14);
insert into esg_api_esgscore (rank, total_industries, esg_score, environment_pillar, governance_pillar, social_pillar, corp_id) values (34, 103, 4, 60, 12, 32, 15);
insert into esg_api_esgscore (rank, total_industries, esg_score, environment_pillar, governance_pillar, social_pillar, corp_id) values (130, 182, 29, 91, 6, 79, 16);
insert into esg_api_esgscore (rank, total_industries, esg_score, environment_pillar, governance_pillar, social_pillar, corp_id) values (125, 466, 47, 77, 20, 87, 17);
insert into esg_api_esgscore (rank, total_industries, esg_score, environment_pillar, governance_pillar, social_pillar, corp_id) values (59, 430, 0, 41, 81, 92, 18);
insert into esg_api_esgscore (rank, total_industries, esg_score, environment_pillar, governance_pillar, social_pillar, corp_id) values (175, 341, 10, 94, 37, 54, 19);
insert into esg_api_esgscore (rank, total_industries, esg_score, environment_pillar, governance_pillar, social_pillar, corp_id) values (149, 412, 5, 13, 73, 96, 20);
insert into esg_api_esgscore (rank, total_industries, esg_score, environment_pillar, governance_pillar, social_pillar, corp_id) values (153, 171, 40, 47, 78, 10, 21);
insert into esg_api_esgscore (rank, total_industries, esg_score, environment_pillar, governance_pillar, social_pillar, corp_id) values (83, 351, 21, 15, 73, 49, 22);
insert into esg_api_esgscore (rank, total_industries, esg_score, environment_pillar, governance_pillar, social_pillar, corp_id) values (140, 384, 17, 70, 32, 42, 23);
insert into esg_api_esgscore (rank, total_industries, esg_score, environment_pillar, governance_pillar, social_pillar, corp_id) values (185, 298, 77, 0, 88, 62, 24);
insert into esg_api_esgscore (rank, total_industries, esg_score, environment_pillar, governance_pillar, social_pillar, corp_id) values (79, 357, 29, 26, 74, 70, 25);
insert into esg_api_esgscore (rank, total_industries, esg_score, environment_pillar, governance_pillar, social_pillar, corp_id) values (13, 403, 61, 16, 32, 13, 26);
insert into esg_api_esgscore (rank, total_industries, esg_score, environment_pillar, governance_pillar, social_pillar, corp_id) values (166, 279, 84, 79, 35, 2, 27);
insert into esg_api_esgscore (rank, total_industries, esg_score, environment_pillar, governance_pillar, social_pillar, corp_id) values (90, 207, 50, 36, 60, 65, 28);
insert into esg_api_esgscore (rank, total_industries, esg_score, environment_pillar, governance_pillar, social_pillar, corp_id) values (172, 103, 42, 78, 12, 40, 29);
insert into esg_api_esgscore (rank, total_industries, esg_score, environment_pillar, governance_pillar, social_pillar, corp_id) values (102, 226, 13, 83, 85, 60, 30);
insert into esg_api_esgscore (rank, total_industries, esg_score, environment_pillar, governance_pillar, social_pillar, corp_id) values (34, 146, 28, 26, 13, 64, 31);
insert into esg_api_esgscore (rank, total_industries, esg_score, environment_pillar, governance_pillar, social_pillar, corp_id) values (25, 485, 72, 48, 3, 15, 32);
insert into esg_api_esgscore (rank, total_industries, esg_score, environment_pillar, governance_pillar, social_pillar, corp_id) values (13, 198, 84, 57, 22, 53, 33);
insert into esg_api_esgscore (rank, total_industries, esg_score, environment_pillar, governance_pillar, social_pillar, corp_id) values (125, 153, 56, 14, 38, 86, 34);
insert into esg_api_esgscore (rank, total_industries, esg_score, environment_pillar, governance_pillar, social_pillar, corp_id) values (73, 302, 18, 63, 43, 1, 35);
insert into esg_api_esgscore (rank, total_industries, esg_score, environment_pillar, governance_pillar, social_pillar, corp_id) values (24, 320, 69, 91, 68, 22, 36);
insert into esg_api_esgscore (rank, total_industries, esg_score, environment_pillar, governance_pillar, social_pillar, corp_id) values (170, 377, 3, 3, 91, 74, 37);
insert into esg_api_esgscore (rank, total_industries, esg_score, environment_pillar, governance_pillar, social_pillar, corp_id) values (159, 381, 88, 4, 13, 69, 38);
insert into esg_api_esgscore (rank, total_industries, esg_score, environment_pillar, governance_pillar, social_pillar, corp_id) values (122, 135, 71, 42, 19, 55, 39);
insert into esg_api_esgscore (rank, total_industries, esg_score, environment_pillar, governance_pillar, social_pillar, corp_id) values (162, 245, 64, 53, 37, 9, 40);
insert into esg_api_esgscore (rank, total_industries, esg_score, environment_pillar, governance_pillar, social_pillar, corp_id) values (143, 193, 97, 53, 11, 59, 41);
insert into esg_api_esgscore (rank, total_industries, esg_score, environment_pillar, governance_pillar, social_pillar, corp_id) values (18, 150, 43, 59, 74, 48, 42);
insert into esg_api_esgscore (rank, total_industries, esg_score, environment_pillar, governance_pillar, social_pillar, corp_id) values (119, 295, 85, 17, 5, 49, 43);
insert into esg_api_esgscore (rank, total_industries, esg_score, environment_pillar, governance_pillar, social_pillar, corp_id) values (123, 176, 83, 86, 67, 83, 44);
insert into esg_api_esgscore (rank, total_industries, esg_score, environment_pillar, governance_pillar, social_pillar, corp_id) values (175, 453, 63, 5, 44, 75, 45);
insert into esg_api_esgscore (rank, total_industries, esg_score, environment_pillar, governance_pillar, social_pillar, corp_id) values (76, 337, 24, 22, 10, 57, 46);
insert into esg_api_esgscore (rank, total_industries, esg_score, environment_pillar, governance_pillar, social_pillar, corp_id) values (153, 486, 76, 54, 83, 27, 47);
insert into esg_api_esgscore (rank, total_industries, esg_score, environment_pillar, governance_pillar, social_pillar, corp_id) values (126, 495, 69, 65, 13, 69, 48);
insert into esg_api_esgscore (rank, total_industries, esg_score, environment_pillar, governance_pillar, social_pillar, corp_id) values (123, 291, 79, 58, 63, 59, 49);
insert into esg_api_esgscore (rank, total_industries, esg_score, environment_pillar, governance_pillar, social_pillar, corp_id) values (158, 184, 63, 87, 73, 51, 50);
insert into esg_api_esgscore (rank, total_industries, esg_score, environment_pillar, governance_pillar, social_pillar, corp_id) values (49, 262, 23, 2, 32, 56, 51);
insert into esg_api_esgscore (rank, total_industries, esg_score, environment_pillar, governance_pillar, social_pillar, corp_id) values (42, 487, 97, 15, 22, 7, 52);
insert into esg_api_esgscore (rank, total_industries, esg_score, environment_pillar, governance_pillar, social_pillar, corp_id) values (160, 161, 98, 90, 68, 80, 53);
insert into esg_api_esgscore (rank, total_industries, esg_score, environment_pillar, governance_pillar, social_pillar, corp_id) values (90, 329, 89, 95, 16, 5, 54);
insert into esg_api_esgscore (rank, total_industries, esg_score, environment_pillar, governance_pillar, social_pillar, corp_id) values (75, 150, 23, 11, 88, 56, 55);
insert into esg_api_esgscore (rank, total_industries, esg_score, environment_pillar, governance_pillar, social_pillar, corp_id) values (84, 406, 42, 38, 96, 79, 56);
insert into esg_api_esgscore (rank, total_industries, esg_score, environment_pillar, governance_pillar, social_pillar, corp_id) values (90, 144, 65, 53, 94, 54, 57);
insert into esg_api_esgscore (rank, total_industries, esg_score, environment_pillar, governance_pillar, social_pillar, corp_id) values (129, 162, 38, 16, 56, 63, 58);
insert into esg_api_esgscore (rank, total_industries, esg_score, environment_pillar, governance_pillar, social_pillar, corp_id) values (194, 185, 29, 91, 89, 94, 59);
insert into esg_api_esgscore (rank, total_industries, esg_score, environment_pillar, governance_pillar, social_pillar, corp_id) values (17, 452, 44, 47, 28, 84, 60);
insert into esg_api_esgscore (rank, total_industries, esg_score, environment_pillar, governance_pillar, social_pillar, corp_id) values (100, 480, 51, 13, 10, 37, 61);
insert into esg_api_esgscore (rank, total_industries, esg_score, environment_pillar, governance_pillar, social_pillar, corp_id) values (187, 231, 3, 73, 78, 38, 62);
insert into esg_api_esgscore (rank, total_industries, esg_score, environment_pillar, governance_pillar, social_pillar, corp_id) values (56, 257, 54, 82, 42, 93, 63);
insert into esg_api_esgscore (rank, total_industries, esg_score, environment_pillar, governance_pillar, social_pillar, corp_id) values (100, 216, 44, 35, 42, 98, 64);
insert into esg_api_esgscore (rank, total_industries, esg_score, environment_pillar, governance_pillar, social_pillar, corp_id) values (151, 162, 28, 20, 66, 79, 65);
insert into esg_api_esgscore (rank, total_industries, esg_score, environment_pillar, governance_pillar, social_pillar, corp_id) values (34, 154, 4, 43, 35, 2, 66);
insert into esg_api_esgscore (rank, total_industries, esg_score, environment_pillar, governance_pillar, social_pillar, corp_id) values (176, 192, 79, 87, 41, 3, 67);
insert into esg_api_esgscore (rank, total_industries, esg_score, environment_pillar, governance_pillar, social_pillar, corp_id) values (167, 436, 73, 33, 18, 46, 68);
insert into esg_api_esgscore (rank, total_industries, esg_score, environment_pillar, governance_pillar, social_pillar, corp_id) values (184, 497, 7, 69, 97, 24, 69);
insert into esg_api_esgscore (rank, total_industries, esg_score, environment_pillar, governance_pillar, social_pillar, corp_id) values (160, 497, 5, 78, 66, 32, 70);
insert into esg_api_esgscore (rank, total_industries, esg_score, environment_pillar, governance_pillar, social_pillar, corp_id) values (19, 467, 96, 82, 6, 28, 71);
insert into esg_api_esgscore (rank, total_industries, esg_score, environment_pillar, governance_pillar, social_pillar, corp_id) values (88, 361, 39, 10, 51, 40, 72);
insert into esg_api_esgscore (rank, total_industries, esg_score, environment_pillar, governance_pillar, social_pillar, corp_id) values (26, 176, 35, 93, 78, 69, 73);
insert into esg_api_esgscore (rank, total_industries, esg_score, environment_pillar, governance_pillar, social_pillar, corp_id) values (15, 491, 40, 48, 50, 62, 74);
insert into esg_api_esgscore (rank, total_industries, esg_score, environment_pillar, governance_pillar, social_pillar, corp_id) values (163, 292, 21, 14, 65, 6, 75);
insert into esg_api_esgscore (rank, total_industries, esg_score, environment_pillar, governance_pillar, social_pillar, corp_id) values (172, 246, 48, 57, 100, 87, 76);
insert into esg_api_esgscore (rank, total_industries, esg_score, environment_pillar, governance_pillar, social_pillar, corp_id) values (112, 422, 16, 16, 26, 1, 77);
insert into esg_api_esgscore (rank, total_industries, esg_score, environment_pillar, governance_pillar, social_pillar, corp_id) values (19, 377, 77, 80, 32, 34, 78);
insert into esg_api_esgscore (rank, total_industries, esg_score, environment_pillar, governance_pillar, social_pillar, corp_id) values (110, 408, 34, 14, 14, 85, 79);
insert into esg_api_esgscore (rank, total_industries, esg_score, environment_pillar, governance_pillar, social_pillar, corp_id) values (200, 482, 82, 4, 80, 91, 80);
insert into esg_api_esgscore (rank, total_industries, esg_score, environment_pillar, governance_pillar, social_pillar, corp_id) values (36, 165, 59, 34, 29, 100, 81);
insert into esg_api_esgscore (rank, total_industries, esg_score, environment_pillar, governance_pillar, social_pillar, corp_id) values (82, 259, 81, 82, 69, 48, 82);
insert into esg_api_esgscore (rank, total_industries, esg_score, environment_pillar, governance_pillar, social_pillar, corp_id) values (112, 126, 3, 4, 33, 65, 83);
insert into esg_api_esgscore (rank, total_industries, esg_score, environment_pillar, governance_pillar, social_pillar, corp_id) values (86, 430, 2, 29, 38, 30, 84);
insert into esg_api_esgscore (rank, total_industries, esg_score, environment_pillar, governance_pillar, social_pillar, corp_id) values (198, 436, 33, 16, 64, 36, 85);
insert into esg_api_esgscore (rank, total_industries, esg_score, environment_pillar, governance_pillar, social_pillar, corp_id) values (133, 239, 15, 85, 13, 38, 86);
insert into esg_api_esgscore (rank, total_industries, esg_score, environment_pillar, governance_pillar, social_pillar, corp_id) values (9, 221, 24, 20, 50, 100, 87);
insert into esg_api_esgscore (rank, total_industries, esg_score, environment_pillar, governance_pillar, social_pillar, corp_id) values (21, 251, 7, 83, 87, 18, 88);
insert into esg_api_esgscore (rank, total_industries, esg_score, environment_pillar, governance_pillar, social_pillar, corp_id) values (96, 493, 98, 11, 78, 10, 89);
insert into esg_api_esgscore (rank, total_industries, esg_score, environment_pillar, governance_pillar, social_pillar, corp_id) values (75, 379, 53, 3, 17, 73, 90);
insert into esg_api_esgscore (rank, total_industries, esg_score, environment_pillar, governance_pillar, social_pillar, corp_id) values (56, 148, 73, 6, 91, 39, 91);
insert into esg_api_esgscore (rank, total_industries, esg_score, environment_pillar, governance_pillar, social_pillar, corp_id) values (51, 481, 70, 41, 28, 8, 92);
insert into esg_api_esgscore (rank, total_industries, esg_score, environment_pillar, governance_pillar, social_pillar, corp_id) values (138, 412, 77, 2, 52, 35, 93);
insert into esg_api_esgscore (rank, total_industries, esg_score, environment_pillar, governance_pillar, social_pillar, corp_id) values (129, 168, 61, 48, 66, 41, 94);
insert into esg_api_esgscore (rank, total_industries, esg_score, environment_pillar, governance_pillar, social_pillar, corp_id) values (147, 198, 83, 86, 60, 79, 95);
insert into esg_api_esgscore (rank, total_industries, esg_score, environment_pillar, governance_pillar, social_pillar, corp_id) values (76, 178, 26, 14, 31, 1, 96);
insert into esg_api_esgscore (rank, total_industries, esg_score, environment_pillar, governance_pillar, social_pillar, corp_id) values (23, 420, 34, 38, 85, 14, 97);
insert into esg_api_esgscore (rank, total_industries, esg_score, environment_pillar, governance_pillar, social_pillar, corp_id) values (24, 400, 34, 66, 4, 15, 98);
insert into esg_api_esgscore (rank, total_industries, esg_score, environment_pillar, governance_pillar, social_pillar, corp_id) values (187, 372, 12, 78, 86, 14, 99);
insert into esg_api_esgscore (rank, total_industries, esg_score, environment_pillar, governance_pillar, social_pillar, corp_id) values (185, 248, 45, 50, 45, 34, 100);
