# Generated by Django 3.2.8 on 2022-06-07 05:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('esg_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Corp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('ticker', models.CharField(max_length=255, unique=True)),
                ('industry_type', models.TextField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.CreateModel(
            name='ESGScore',
            fields=[
                ('rank', models.IntegerField()),
                ('total_industries', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('esg_score', models.IntegerField()),
                ('environment_pillar', models.IntegerField()),
                ('governance_pillar', models.IntegerField()),
                ('social_pillar', models.IntegerField()),
                ('corp', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='esg_api.corp')),
            ],
        ),
    ]
